{"name": "Если создать пользователя с логином, который уже есть, возвращается ошибка.", "status": "passed", "start": 1728216686282, "stop": 1728216686376, "uuid": "dba380e1-8885-487f-b198-89397f6d5724", "historyId": "d1cab6b93087c5ef26dafe71eda35ba4", "testCaseId": "d1cab6b93087c5ef26dafe71eda35ba4", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_duplicate_courier_login_false", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "WIN-4TEUO1LLUHP"}, {"name": "thread", "value": "292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}