{"name": "Текст ошибки создания дубликата курьера \"Этот логин уже используется.\"", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется.'\n  \n  - Этот логин уже используется.\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <test_create_courier.TestCreateCourier object at 0x0000021439585E20>\n\n    @allure.title('Текст ошибки создания дубликата курьера \"Этот логин уже используется.\"')\n    def test_create_duplicate_courier_false(self):\n        payload = {\"login\": registrated_login,\n                   \"password\": registrated_password,\n                   \"firstName\": registrated_firstName}\n        response = requests.post(PAGE_CREATE_COURIER, json=payload)\n>       assert response.json().get(\"message\") == \"Этот логин уже используется.\"\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется.'\nE         \nE         - Этот логин уже используется.\nE         + Этот логин уже используется. Попробуйте другой.\n\ntests\\test_create_courier.py:30: AssertionError"}, "start": 1728250378093, "stop": 1728250378234, "uuid": "5981ce91-7177-454f-9683-604f16b0bb11", "historyId": "40e9ecc9a5f744043ddebc617a5f4e51", "testCaseId": "40e9ecc9a5f744043ddebc617a5f4e51", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_duplicate_courier_false", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "WIN-4TEUO1LLUHP"}, {"name": "thread", "value": "13788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}