{"name": "Если создать пользователя с логином, который уже есть, возвращается ошибка.", "status": "passed", "start": 1728216219505, "stop": 1728216219615, "uuid": "12d9f233-3629-445f-9a05-256e13e475d8", "historyId": "d1cab6b93087c5ef26dafe71eda35ba4", "testCaseId": "d1cab6b93087c5ef26dafe71eda35ba4", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_duplicate_courier_login_false", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "WIN-4TEUO1LLUHP"}, {"name": "thread", "value": "24004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}