{"name": "Если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "start": 1728216000141, "stop": 1728216000250, "uuid": "1b90df64-1b9a-410f-b97b-6bcf764881f3", "historyId": "ca609b376c8df0d6336f167288c3af7e", "testCaseId": "ca609b376c8df0d6336f167288c3af7e", "fullName": "tests.test_login_courier.TestCreateLogin#test_login_wrong_data_error_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCreateLogin"}, {"name": "host", "value": "WIN-4TEUO1LLUHP"}, {"name": "thread", "value": "12536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}